defconfig: flo: Enable CONFIG_ANDROID_BINDER_IPC_32BIT
 * Use the old 32-bits binder API as our kernel runs on
	ARM 32bits, it should not compile  elements in 64bits,
	which would end in failures with following output:
	"undefined reference to `__get_user_bad'"

(cherry picked from commit e0ee4f81d7d59e0eb5220ea9414a2286e8d81c06)